// Ben Smith
// p1.cpp
// 1/26/2017

// PURPOSE: Allows the user to play a game where the objective is to guess the
//  hidden number generated by the computer.

// INPUTS: Guesses by the user.

// PROCESSING: Random number genration 1-100(inclusive). Keeps track of how many
//  guesses the user has attempted. Determines if the user has correctly guessed
//  the hidden number.

// OUTPUTS: If the user's guess was too high or too low. When the user guesses
//  the hidden number correctly. How many guesses it took to correctly guess
//  the hidden value.

// EXAMPLES:
// Enter a number between 1 - 100:
// 5
// TOO LOW guess again:
// 50
// TOO HIGH guess again:
// 25
// Correct! You won with  3 guesses
// Enter a number 1 - 100:
// 101
// Invalid number
// Enter a numer between 1 - 100:


#include <iostream>
#include <cstdlib>

using namespace std;

const int MAX_VALUE = 100; // Maximum value that can be entered by the user
const int MIN_VALUE = 1;   // Minimum value that can be entered by the user

int main(){

  unsigned seed;  // used to randomly generate a number 
  seed = time(0);
  srand(seed);

 int randomNumber, userGuess, numberOfGuesses;
 
 numberOfGuesses = 0; // stores the guesses of the user
 randomNumber = rand() % 100 +1; // Creates a random number between 1-100

  cout << "Enter a number between 1 - 100: ";
  cin >> userGuess; // user input 

  while(userGuess != randomNumber){
    if(userGuess < MIN_VALUE || userGuess > MAX_VALUE){ // Validates user input 
      cout << "Error Invalid input\n" << "Enter a number between 1 - 100: ";
      cin >> userGuess;
    }
    else if(userGuess > randomNumber){ // If the user guess is too high
      cout << "\nTOO HIGH guess again: ";
      numberOfGuesses += 1; // increases the guess count by 1 
      cin >> userGuess;
    }
    else{
      cout << "\nTOO LOW guess again: ";
      numberOfGuesses += 1;
      cin >> userGuess; 
    }    
  }
  cout << "\nCorrect! You have won with " << numberOfGuesses << " guesses"<< endl; 
  return 0;  
}

